# Generated by Django 3.2.4 on 2021-06-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footballer',
            new_name='Article',
        ),
    ]
