# Generated by Django 3.2.4 on 2021-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='electronics', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
